### PR TITLE
Split file name to get the correct resource

### LINKED ISSUE #3: Reach files spout/bolt
Issue to reach spout or bolt mc2 files that are in a different repository than the .sh file
Step to reproduce, run the given example in a clean folder.
```
./toporun.sh -l -t tmp ../warpscript/warpscript-spout.mc2 ../warpscript/warpscript-bolt.mc2
```

### PR DESCRIPTION
**Pull request by aurrelhebert**
This closes #3

### CODE REVIEW

**Comment by hbs** [comment]
Why is that necessary? Does it mean the path to your files is incorrect in the jar generated by toporun.sh?

**Comment by aurrelhebert** [comment]
Yes

**Comment by hbs** [comment]
Then this is not the way to solve it.

The fix should be in toporun.sh so the path in the jar is the canonical one.

And as of now toporun.sh MUST be run from the warp10-storm root directory otherwise it will not find the warp10-storm jar.

**Comment by aurrelhebert** [comment]
The main issue isn't the path inside the jar. It's just that with the current version of toporun.sh, it forces the user to put all it's files in the same folder containing toporun.sh.

**Comment by hbs** [comment]
That's not the case, your issue was because your path contained '..'

You can run toporun.sh from the root warp10-storm and reference config or mc2 files which are in other directories, you just can't do it using '..' because we don't canonicalize the file paths.

**Comment by aurrelhebert** [comment]
Yes that's why I open an issue because all the files have to be in the same
directory (or subdirectory) than toporun.sh. Neither relative or absolute
path works.
It would be nice not to force this, and to be able to load a file from
somewhere else locally.

**Comment by hbs** [comment]
Files have to be accessible from the directory you're in when you run toporun.sh via a relative path which does not contain '..' or '.'.

As I've said, this should be addressed in toporun.sh, not in the warp10-storm java classes.

**Pull request closed without merging**
